language: c
dist: xenial
sudo: true
compiler:
  - gcc
addons:
  apt:
    sources:
      - sourceline: 'deb http://packages.ros.org/ros/ubuntu xenial main'
        key_url: http://packages.ros.org/ros.key
    packages:
      - dpkg-dev
      - devscripts
install:
  - mk-build-deps --install debian/control
before_script:
  - git fetch origin master:master
  - debian/rules make-orig-tar
script:
  - dpkg-buildpackage -tc -uc -us
after_success:
  - for d in ../*.deb; do dpkg-deb -I $d; dpkg-deb -c $d; done

