language: c
dist: trusty
sudo: false
compiler:
  - gcc
addons:
  apt:
    packages:
      - dpkg-dev
      - debhelper
      - python-all
      - python3-all
      - fakeroot
      - python-setuptools
      - python3-setuptools
      - dh-python
before_script:
  - git fetch origin master:master
  - debian/rules make-orig-tar
script:
  - dpkg-buildpackage -tc -uc -us -i\\..*
after_success:
  - for d in ../*.deb; do dpkg-deb -I $d; dpkg-deb -c $d; done

